[fix]: Riot API 활용 로직, DI해서 사용할 수 있도록 로직 변경 (#141)
## 작업사항
1. 기존 Riot API 활용을 위해 함수를 import하는 방식으로 사용했음.
2. 하지만 나중에 Riot API를 활용하는 로직이 많아질 것으로 판단, RiotAPI의 로직을 담당하는 클래스를 만들어서 역할과 책임을 부여
3. 수정하는 과정에서, 아래와 같은 오류가 출력됐고, 이는 관계된 이슈, PR 링크에 해당하는 것처럼 내용을 수정함.

```
Error: The default Firebase app already exists. 
This means you called initializeApp() more than once without providing an app name as the second argument. 
In most cases you only need to call initializeApp() once. 
But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
```

## 관계된 이슈, PR 
https://velog.io/@doohyunlm/%EC%97%90%EB%9F%AC-Lambdanodejs-firebase